package com.innocuoussymmetry.REST2.db;

import java.sql.*;

public class DBConn {
    private Connection conn;
    private final String seedQuery = """
        CREATE TABLE IF NOT EXISTS things (
            id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name VARCHAR
        );
        
        CREATE TABLE IF NOT EXISTS stuff (
            id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name VARCHAR
        );
    """;
    public DBConn(String constring) {
        try {
            this.conn = DriverManager.getConnection(constring);
        } catch (SQLException e) {
            System.out.println(e);
        }
    }

    public void insert(String name, String table) {
        try {
            PreparedStatement st = conn.prepareStatement("INSERT INTO ? (name) VALUES (?);");
            st.setString(1, table);
            st.setString(2, name);
            st.execute();
            st.close();
        } catch (SQLException e) {
            System.out.println(e);
        }
    }

    private void setup() {
        try {
            Statement st = conn.createStatement();
            st.execute(this.seedQuery);
            st.close();
        } catch (SQLException e) {
            System.out.println(e);
        }
    }

    private void seed() {
        this.setup();
        this.insert("tea", "things");
        this.insert("cat", "stuff");
        this.insert("apple", "things");
    }

    public static void main(String[] args) {
        new DBConn("jdbc:postgresql://localhost:5432/rest2db?username=postgres&password=postgres").seed();
    }
}
